FROM ruby:2.3.1

ADD ./ /src
WORKDIR /src
RUN gem install bundler
RUN bundle install
ENTRYPOINT ["bundle","exec"]
CMD ["./serve_images.rb", "-p", "80", "-o", "0.0.0.0"]

EXPOSE 80
VOLUME /data
ENV DATA_DIR /data
